In [1]:
import pandas as pd

In [4]:
PATH_FILE_SCORE_FILTRO_ALGORITMO = './scoreFiltratiFinaliCsvSuperFiltraggio.csv'
PATH_FILE_SCORE_FILTRO_MANUALE = './scoreFiltratiFinaliExcelSuo.csv'
PATH_FILE_SCORE_FULL = './scoreCsvDatasetFinale.csv'

scores_filtro_algoritmo = pd.read_csv(PATH_FILE_SCORE_FILTRO_ALGORITMO)
scores_filtro_manuale = pd.read_csv(PATH_FILE_SCORE_FILTRO_MANUALE)
scores_filtro_full = pd.read_csv(PATH_FILE_SCORE_FULL)

In [39]:
def calcola_id_soggetto_da_utente(u):
    return u.split("_")[0]

def calcola_num_acquisizione_da_utente(u):
    return int(u.split("_")[1])

In [40]:
scores_filtro_full['Primo soggetto'] = scores_filtro_full['Utente1'].apply(lambda u: calcola_id_soggetto_da_utente(u))
scores_filtro_full['Secondo soggetto'] = scores_filtro_full['Utente2'].apply(lambda u: calcola_id_soggetto_da_utente(u))

In [29]:
set_filtro_algoritmo = set(list(scores_filtro_algoritmo.Utente1.unique()) +  list(scores_filtro_algoritmo.Utente2.unique()))
set_filtro_manuale = set(list(scores_filtro_manuale.Utente1.unique()) + list(scores_filtro_manuale.Utente2.unique()))
set_full = set(list(scores_filtro_full.Utente1.unique()) + list(scores_filtro_full.Utente2.unique()))

In [96]:
filtrati_filtro_algoritmo = set(set_full - set_filtro_algoritmo)
filtrati_filtro_manuale = set(set_full - set_filtro_manuale)

In [106]:
df_acquisizioni = pd.DataFrame()
for acquisizione in filtrati_filtro_manuale:
    df_acquisizione = scores_filtro_full[(scores_filtro_full.Utente1 == acquisizione) |  (scores_filtro_full.Utente2 == acquisizione)]
    df_acquisizione = df_acquisizione[df_acquisizione['Primo soggetto'] == df_acquisizione['Secondo soggetto']] 
    media_score = df_acquisizione.ScoreML.mean()
    min_score = df_acquisizione.ScoreML.min()
    perc_min_score = len(df_acquisizione[df_acquisizione.ScoreML <= 0.25]) / len(df_acquisizione)
    riga_df = pd.DataFrame(data={'acquisizione': [acquisizione], 'score_medio': [media_score], 'perc_min_score': [perc_min_score]})
    df_acquisizioni = pd.concat([df_acquisizioni, riga_df])

In [107]:
a = df_acquisizioni.sort_values(by='score_medio')
a = a.reset_index(drop=True)

In [105]:
a.style

In [71]:
s.ScoreML.mean()

0.4195571557533719

In [72]:
175/300

0.5833333333333334

In [ ]:
60%

In [108]:
a.style

In [112]:
57/225

0.25333333333333335

In [113]:
82/300

0.2733333333333333

In [ ]:
### SUO
Righe eliminate: 225
25% sotto 0.30 
86% sotto media di score del dataset (0.42)

### Nostro
Righe eliminate: 300
27% sotto 0.30
60% sotto media di score del dataset (0.42)