In [1]:
import pandas as pd

In [7]:
PATH_CSV_LABELS = 'tabellaPseudoLabelsDatasetCompleto.csv'
PATH_EXCEL_SUO_LABELS = '../Nuovi Dati/Dataset_Sensori_Da_Mat.csv'

In [6]:
df_labels = pd.read_csv(PATH_CSV_LABELS)
df_labels

             Acquisizione     Label  Label_norm
0    AgatielloRoberto_000  0.648876   50.428711
1    AgatielloRoberto_001  0.759503   61.300294
2    AgatielloRoberto_002  0.747500   60.120716
3    AgatielloRoberto_003  0.818899   67.137182
4    AgatielloRoberto_004  0.825895   67.824714
..                    ...       ...         ...
713       VenafraSara_010  0.638803   49.438784
714       VenafraSara_011  0.789886   64.286081
715       VenafraSara_012  0.789531   64.251135
716       VenafraSara_013  0.766965   62.033559
717       VenafraSara_014  0.815002   66.754219

[718 rows x 3 columns]

In [19]:
df_excel_suo = pd.read_csv(PATH_EXCEL_SUO_LABELS)
lista_acquisizioni_filtrate = set(df_excel_suo.Acquisizione1.unique()) | set(df_excel_suo.Acquisizione2.unique())
lista_acquisizioni_filtrate = [i.replace('.dat', '') for i in lista_acquisizioni_filtrate]

In [20]:
lista_acquisizioni = list(set(df_labels.Acquisizione.unique()) - set(lista_acquisizioni_filtrate))

PATH_FILE_SCORE = '../scoreCsvDatasetFinale.csv'
scores = pd.read_csv(PATH_FILE_SCORE)
scores = scores[~scores.Utente1.isin(lista_acquisizioni)]
scores = scores[~scores.Utente2.isin(lista_acquisizioni)]
scores

                     Utente1               Utente2   ScoreML
0       AgatielloRoberto_000  AgatielloRoberto_001  0.526569
1       AgatielloRoberto_000  AgatielloRoberto_002  0.491637
2       AgatielloRoberto_000  AgatielloRoberto_003  0.525314
3       AgatielloRoberto_000  AgatielloRoberto_004  0.516008
4       AgatielloRoberto_000  AgatielloRoberto_005  0.567200
...                      ...                   ...       ...
258116       VenafraSara_012       VenafraSara_014  0.593949
258117       VenafraSara_012    VenturaAlessio_000  0.121388
258118       VenafraSara_013       VenafraSara_014  0.599829
258119       VenafraSara_013    VenturaAlessio_000  0.121099
258120       VenafraSara_014    VenturaAlessio_000  0.113802

[121771 rows x 3 columns]

In [21]:
scores.to_csv('../scoreFiltratiFinaliExcelSuo.csv' ,index=False)